# Generated by Django 5.0.1 on 2024-02-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_rename_preperation_time_meal_preparation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
    ]
