# Generated by Django 5.0.1 on 2024-01-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
    ]
