# Generated by Django 5.0.2 on 2024-02-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
    ]
